version: '2'

services:
  showdoc:
    restart: always
    image: william0wang/showdoc:latest
    volumes:
      - ./data/uploads:/var/www/html/Public/Uploads
      - ./data/Sqlite:/var/www/html/Sqlite
      - ./data/install.lock:/var/www/html/install/install.lock
    ports:
      - "11380:80"
